### ISSUE TITLE
<hr> invisible on black background

### ISSUE THREAD

**Issue by TheHardew** [foobnix/LibreraReader#1158]
\<hr> is rendered in most browsers as a horizontal line, librera does not render it

**Comment by TheHardew** [comment]
It renders them as black lines so in night mode (amoled black, black background) they are invisible.
Maybe using the color of the text as default makes more sense?

**Comment by TheHardew** [comment]
Duplicate of #961

**Comment by foobnix** [comment]
fixed in beta.librera.mobi please check on your book

**Comment by TheHardew** [comment]
works, thank you!

**Comment by HannahBanana1312** [comment]
I don't think its a duplicate of my issue (#961) since the update didn't fix my issue

**Comment by foobnix** [comment]
please check beta.librera.mobi I have fixed
