### ISSUE TITLE
Bookmarks can't be seen on day theme color

### ISSUE THREAD

**Issue by nutzlichsein** [foobnix/LibreraReader#1340]
Hi, when reading books using day theme, the bookmarks on top of the page can't be read. The font becomes white like the background. The bookmarks are OK using night theme.

I don't know if it's already a known issue or that I have something wrong set in my Librera. I hope I can find solution for this.

Thank you for this great app!

---

**Step to reproduce**
1. Open a book that has bookmarks
2. set Day theme color (black text on white background)

**Technical info**
Librera Reader version: 8.9.182-fdroid
Android OS: LineageOS 21
Phone: Oneplus 6

**Screenshots**
![Screenshot_2024-12-17_12-33-35.png](https://github.com/user-attachments/assets/a69a2455-714b-4113-8f9e-3a047b56ca8c)

![Screenshot_2024-12-17_12-34-29.png](https://github.com/user-attachments/assets/355ff299-a18a-46f4-ac7c-37ba2dad83e5)

![Screenshot_2024-12-17_12-36-33.png](https://github.com/user-attachments/assets/d57b45e0-5d8f-4aaf-acb7-8dd45c25b403)

**Comment by vaibhav423** [comment]
is it fixed @nutzlichsein ?

**Comment by vaibhav423** [comment]
@nutzlichsein the problems seems to be from version  higher than 8.9.133 , works well on 8.9.133 and lower

**Comment by nutzlichsein** [comment]
> @nutzlichsein the problems seems to be from version  higher than 8.9.133 , works well on 8.9.133 and lower

I am using 8.9.182-fdroid and this problem exists

![Screenshot_2025-03-07-20-32-38-888_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/381e9e91-3be9-42a0-bc86-19ffb001de0b)

**in day mode, the bookmarks are not visible**
![Screenshot_2025-03-07-20-30-51-813_com.foobnix.pro.pdf.reader.jpg](https://github.com/user-attachments/assets/f099849c-7bfa-4c46-9f85-50f834f9d812)

**in night mode, the bookmarks are visible**
![Screenshot_2025-03-08-08-50-01-262_com.foobnix.pro.pdf.reader.jpg](https://github.com/user-attachments/assets/7052bbe1-ed97-485c-9a54-6ff663c0c3cf)

**Comment by vaibhav423** [comment]
install 8.9.133 from releases

**Comment by nutzlichsein** [comment]
> install 8.9.133 from releases

got it brother. I Installed 8.9.133 from releases and it works... will it be resolved in newer version? because I had 8.9.182 (from the number it's supposed to be newer than .133) but it had the issue...

**Comment by vaibhav423** [comment]
@foobnix can u please look this out it is still not fixed . The problem is only in day mode where the page number inside the bookmark is white in color.

**Comment by foobnix** [comment]
Thank you for remider, fixed in beta.librera.mobi

<img width="485" height="731" alt="Image" src="https://github.com/user-attachments/assets/bb3336f4-e19d-4741-a0d7-afd12849af81" />
<img width="485" height="731" alt="Image" src="https://github.com/user-attachments/assets/00001caa-c411-4389-aed5-ca12d3670511" />

**Comment by vaibhav423** [comment]
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/ad444c0d-54ea-4e2b-a21e-989169614ac1" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/4859dc8d-ecaa-44ed-b48c-c5e15bb20dc4" />

awesome now it looks great .

I know it's only me 😅 , but the white color around the bookmark icon hurts in night mode . 😛 I will take it  for now

anyways as always great work 👍
