### ISSUE TITLE
Search OPDS feed (Calibre-Web)

### ISSUE THREAD

**Issue by rg9400** [foobnix/LibreraReader#659]
I recently purchased Librera Pro, and I am really liking it. I was just wondering if there was a way to search when using an OPDS feed, namely from Calibre-Web (not to be confused with Calibre's own OPDS feed) https://github.com/janeczku/calibre-web.

The feed itself works fine, I can see covers, series info, genres, formats, summaries, etc. in the catalog. Just cannot find a way to search, and I was wondering if it was missing from Librera completely, I had missed how to do it, or there is some specific incompatibility with Calibre-Web. The feed can be searched in some other apps like FBReader, but I would much prefer to use Librera if possible

**Comment by PLkTZSkZ** [comment]
Hi,
I was wondering about the same thing and it turned out that this is not an issue with librera but with calibre-web itself. 
It was addressed in this issue https://github.com/janeczku/calibre-web/issues/1845 and after I changed it after this commit https://github.com/janeczku/calibre-web/commit/33bdc07f5599c4c0e1531a9b49b41a1a079094ec on my instance, I could use the search in librera. 

The only thing still not perfect is that the search cannot use spaces (as in hitting spacebar) and this this seems to be on librera. (since my koreader is substituting spaces to %s it works there but in librera spaces have to be substituted directly with userinput with _ or % like this: search_term, search%term) 
But with using _ or % instead of spaces you can then even search for multiword strings like author and title.

So I think this issue here can be closed. :)

Greetings

**Comment by vinser** [comment]
Sorry for necroposting, but the issue is still alive
@PLkTZSkZ This is librera reader issue and users can't do saerches not only on calibre that was patched but on such OPDS resourses as Project Gutenberg
This librera bug is clearly explained in  #1293

**Comment by itsjakobx** [comment]
OPDS without Search is sadly not very useful, as you have to potentially scroll through thousands of books to find what you need

I am using librera with booklore as opds server, and search also doesn't work there. With other programs such as KOReader it does.
